// Generated by CoffeeScript 1.9.1
(function() {
  var build, exec, print, ref, spawn;

  ref = require('child_process'), spawn = ref.spawn, exec = ref.exec;

  print = require('util').print;

  build = function(watch, callback) {
    var coffee, options;
    if (typeof watch === 'function') {
      callback = watch;
      watch = false;
    }
    options = ['-c', '-o', 'lib', 'src'];
    if (watch) {
      options.unshift('-w');
    }
    coffee = spawn('coffee', options);
    coffee.stdout.on('data', function(data) {
      return print(data.toString());
    });
    coffee.stderr.on('data', function(data) {
      return print(data.toString());
    });
    return coffee.on('exit', function(status) {
      if (status === 0) {
        return typeof callback === "function" ? callback() : void 0;
      }
    });
  };

  task('build', 'Compile CoffeScript source files', function() {
    return build();
  });

  task('watch', 'Recompile CoffeScript when source files are modified', function() {
    return build(true);
  });

  task('test', 'Run the test suite', function() {
    return build(function() {
      var reporters;
      reporters = require('nodeunit').reporters;
      process.chdir(__dirname);
      return reporters["default"].run(['test']);
    });
  });

}).call(this);
